global_defs {
    enable_script_security
    script_user root
}

vrrp_script chk_web {
    script "/usr/local/bin/check_web.sh"
    interval 3          # Каждые 3 секунды
    timeout 2
    weight -20          # Если скрипт возвращает !=0, то приоритет уменьшается на 20
    fall 2              # Нужно 2 неудачных проверки для переключения
    rise 2              # Нужно 2 успешных проверки для возврата
}

vrrp_instance VI_1 {
    interface enp0s8
    state MASTER
    virtual_router_id 51
    priority 100        # Высокий приоритет (MASTER по умолчанию)
    advert_int 1

    authentication {
        auth_type PASS
        auth_pass secret12
    }

    virtual_ipaddress {
        192.168.56.100/24
    }

    track_script {
        chk_web
    }
}

